objects := main.o
def = $(objects)
imd := $(objects)

$(info defered variable, $(def)) # main.o
$(info immediate variable, $(imd)) # main.o
objects += more.o
$(info defered variable after append, $(def)) # main.o more.o
$(info immediate variable after append, $(imd)) # main.o


