# environment variable "HOME" should be /home/jiangrui
# but makefile variable "HOME" override it
# but "make --environment-overrides (-e)" will override makefile variable

# XXX: try "make" and "make -e"
HOME = /root

$(info HOME, $(HOME))
